name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Echo AWS Access Key (Debug Step)
        run: echo ${{ secrets.AWS_ACCESS_KEY_ID }}

      - name: Verify AWS Secrets Presence (Debug Step)
        run: |
          if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
            echo "AWS_ACCESS_KEY_ID secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
            echo "AWS_SECRET_ACCESS_KEY secret is not set"
            exit 1
          fi
          echo "AWS secrets are set"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Verify AWS credentials
        run: aws sts get-caller-identity

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform

      - name: Plan Terraform
        run: terraform plan -out=tfplan
        working-directory: terraform

      - name: Apply Terraform
        run: terraform apply -auto-approve tfplan
        working-directory: terraform

      - name: Upload plan file
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: terraform/tfplan
